language: php
php:
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"
script:
  - phpunit -c tests/phpunit.xml
  #- phpunit --bootstrap test/unittests/translationTest.php --coverage-text test

after_success:
  - coveralls
