language: php
php:
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"

#script:

#  - phpunit -c tests/phpunit.xml
  #- phpunit --coverage-phpunit tests/phpunit.xml

  #- phpunit --configuration="tests/phpunit.xml" --include-path="tests/"
  #- phpunit --coverage-clover build/logs/clover.xml
  #- phpunit --bootstrap test/unittests/translationTest.php --coverage-text test
  #- vendor\bin\phpunit --bootstrap bootstrap.php opencart\admin to run tests in admin folder

#after_success:
  #- travis_retry php coveralls.phar -v
#  - coveralls
#  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'

#before_install:
#- composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:dev-master
#- composer install --dev

script:
#- ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
- phpunit -c tests/phpunit.xml

after_script:
- php vendor/bin/coveralls -v

notifications:
  slack:
    on_success: never
    on_failed: never
