language: php
php:
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"

#script:
#- phpunit -c tests/phpunit.xml

#after_script:
#- php ./vendor/bin/coveralls -v

before_script:
 - wget http://getcomposer.org/composer.phar
 #- php composer.phar install --dev --no-interaction

script:
 - mkdir -p build/logs
 #- phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v

notifications:
  slack:
    on_success: never
    on_failed: never
