language: php
php:
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"

# install:
#   - pip install coveralls

install:
  - composer require satooshi/php-coveralls:~0.6@stable

before_script:
  - mkdir -p build/logs
script:
  - phpunit -c tests/phpunit.xml
  - phpunit --configuration="tests/phpunit.xml" --include-path="tests/"
  - phpunit --coverage-clover build/logs/clover.xml
  #- phpunit --bootstrap test/unittests/translationTest.php --coverage-text test
  #- vendor\bin\phpunit --bootstrap bootstrap.php opencart\admin to run tests in admin folder

after_success:
  - coveralls
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
