language: php
php:
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"
script:
  - phpunit -c tests/phpunit.xml
  #- phpunit --bootstrap test/unittests/translationTest.php --coverage-text test
  #- vendor\bin\phpunit --bootstrap bootstrap.php opencart\admin to run tests in admin folder 

after_success:
  #- coveralls
  - php vendor/bin/coveralls -v
