language: php
php:
  - "7.0"
  - "5.6"
  - "5.5"
  #- "5.4"

#script:
#- phpunit -c tests/phpunit.xml

before_install:
- composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:dev-master
- composer install --dev

# Composer package installation
install:
  # Install composer packages, will also trigger dump-autoload
  - travis_retry composer install --no-interaction
  # Install coveralls.phar
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version

before_script:
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install --dev --no-interaction

script:
 - mkdir -p build/logs
 - phpunit -c tests/phpunit.xml
 #- phpunit --coverage-clover build/logs/clover.xml
 - phpunit --bootstrap tests/unittests/translationTest.php --coverage-text test
 - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
 #- coveralls -v
 - travis_retry php coveralls.phar -v
 - php vendor/bin/coveralls -v


notifications:
 slack:
    on_success: never
    on_failed: never
